### ISSUE TITLE
License on the data?

### ISSUE THREAD

**Issue by JamesLMilner** [zeke/nearby-cities#3]
Where did this data come from? Is it open?

**Comment by zeke** [comment]
https://github.com/zeke/all-the-cities

via

https://www.npmjs.com/package/cities1000

via

http://download.geonames.org/export/dump/

> The GeoNames geographical database covers all countries and contains over eleven million placenames that are available for download free of charge.

> This work is licensed under a [Creative Commons Attribution 3.0 License](https://creativecommons.org/licenses/by/3.0/)

**Comment by JamesLMilner** [comment]
Sweet, thanks for clarification. Might be worth chucking it in the readme? :)
